# This yaml file is for setup a wordpress environment for wordpress theme development
version: '2.0'
  
services:
  
  # MySQL 
  db:
    build: 
      context: ./bin/db
    image: theme_dev_mysql
    container_name: theme_dev_mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - dev_nt
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql

  # WordPress
  wp:
    build: 
      context: ./bin/wp
    image: theme_dev_wp
    container_name: theme_dev_wp
    volumes:
      - wp-vol:/var/www/html/
      - ./wp-content/:/var/www/html/wp-content 
    ports:
      - 8888:80
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      LOCAL_USER_ID: ${LOCAL_USER_ID}
      LOCAL_USER_NAME: ${LOCAL_USER_NAME}
    networks:
      - dev_nt
    stdin_open: true
    tty: true

  # PHP-MyAdmin   
  php-myadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: theme_dev_phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db:3306
      PMA_PORT: 3306 
    networks:
      - dev_nt
    links:
      - db

# using this named volume ensures db's hang around between "up's"
volumes:
    mysql-vol:
    wp-vol:
networks:
    dev_nt:
